# Generated by Django 3.2 on 2022-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='warehouses',
            name='organizations',
        ),
        migrations.AddField(
            model_name='organizations',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='entity_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
