# Generated by Django 3.2 on 2022-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20220507_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
