# Generated by Django 3.2 on 2022-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_addresses_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='store_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=45),
        ),
    ]
