# Generated by Django 5.1.3 on 2024-11-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_stores_store_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='entity_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_currency',
            field=models.CharField(choices=[('CHOOSE_CURRENCY', 'Choose Currency'), ('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=45),
        ),
    ]
