# Generated by Django 5.1.3 on 2024-11-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_addresses_entity_id_addresses_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizations',
            table='organizations',
        ),
    ]
