# Generated by Django 5.1.3 on 2024-11-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizations_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresses',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='stores',
            table='stores',
        ),
        migrations.AlterModelTable(
            name='warehouses',
            table='warehouses',
        ),
    ]
