# Generated by Django 5.1.3 on 2024-11-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Usertoken',
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='usertoken',
        ),
    ]
