# Generated by Django 5.1.3 on 2024-11-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_token_usertoken_alter_usertoken_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usertoken',
            new_name='UserTokens',
        ),
        migrations.AlterModelTable(
            name='usertokens',
            table='user_tokens',
        ),
    ]
